### Import Libraries

In [171]:

import numpy as np
import pandas as pd
import urllib.request
from numpy.linalg import inv



### Question 1

In [178]:
np.__version__

'1.21.5'

### Question 2

#### Import Data

In [3]:
url = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv'
filename = 'carprice.csv'
urllib.request.urlretrieve(url, filename)

('carprice.csv', <http.client.HTTPMessage at 0x16ed7be39a0>)

In [144]:
df = pd.read_csv('carprice.csv')

In [5]:
df.head(5)

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [6]:
df.describe

<bound method NDFrame.describe of           Make       Model  Year                Engine Fuel Type  Engine HP  \
0          BMW  1 Series M  2011     premium unleaded (required)      335.0   
1          BMW    1 Series  2011     premium unleaded (required)      300.0   
2          BMW    1 Series  2011     premium unleaded (required)      300.0   
3          BMW    1 Series  2011     premium unleaded (required)      230.0   
4          BMW    1 Series  2011     premium unleaded (required)      230.0   
...        ...         ...   ...                             ...        ...   
11909    Acura         ZDX  2012     premium unleaded (required)      300.0   
11910    Acura         ZDX  2012     premium unleaded (required)      300.0   
11911    Acura         ZDX  2012     premium unleaded (required)      300.0   
11912    Acura         ZDX  2013  premium unleaded (recommended)      300.0   
11913  Lincoln      Zephyr  2006                regular unleaded      221.0   

       Engine Cyl

### Question 3

In [20]:
df['Make'].value_counts()

Chevrolet        1123
Ford              881
Volkswagen        809
Toyota            746
Dodge             626
Nissan            558
GMC               515
Honda             449
Mazda             423
Cadillac          397
Mercedes-Benz     353
Suzuki            351
BMW               334
Infiniti          330
Audi              328
Hyundai           303
Volvo             281
Subaru            256
Acura             252
Kia               231
Mitsubishi        213
Lexus             202
Buick             196
Chrysler          187
Pontiac           186
Lincoln           164
Oldsmobile        150
Land Rover        143
Porsche           136
Saab              111
Aston Martin       93
Plymouth           82
Bentley            74
Ferrari            69
FIAT               62
Scion              60
Maserati           58
Lamborghini        52
Rolls-Royce        31
Lotus              29
Tesla              18
HUMMER             17
Maybach            16
Alfa Romeo          5
McLaren             5
Spyker    

### Question 4

In [87]:
q3= df[['Make','Model']]
q3

Make       Model
0          BMW  1 Series M
1          BMW    1 Series
2          BMW    1 Series
3          BMW    1 Series
4          BMW    1 Series
...        ...         ...
11909    Acura         ZDX
11910    Acura         ZDX
11911    Acura         ZDX
11912    Acura         ZDX
11913  Lincoln      Zephyr

[11914 rows x 2 columns]

In [93]:
audi_mode = q3[(q3['Make']=='Audi')]
audi_mode

Make Model
17     Audi   100
18     Audi   100
19     Audi   100
20     Audi   100
21     Audi   100
...     ...   ...
10901  Audi   TTS
10902  Audi   TTS
11178  Audi    V8
11179  Audi    V8
11180  Audi    V8

[328 rows x 2 columns]

In [97]:
audi_mode['Model'].unique().size

34

### Question 5

In [106]:
df.head(1)

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135

In [104]:
df['Model'].isna().value_counts()

False    11914
Name: Model, dtype: int64

In [107]:
df['Make'].isna().value_counts()

False    11914
Name: Make, dtype: int64

In [108]:
df['Year'].isna().value_counts()

False    11914
Name: Year, dtype: int64

In [110]:
df['Engine HP'].isna().value_counts()

False    11845
True        69
Name: Engine HP, dtype: int64

In [111]:
df['Engine Cylinders'].isna().value_counts()

False    11884
True        30
Name: Engine Cylinders, dtype: int64

In [113]:
df['Transmission Type'].isna().value_counts()

False    11914
Name: Transmission Type, dtype: int64

In [114]:
df['Driven_Wheels'].isna().value_counts()

False    11914
Name: Driven_Wheels, dtype: int64

In [115]:
df['Number of Doors'].isna().value_counts()

False    11908
True         6
Name: Number of Doors, dtype: int64

In [116]:
df['Market Category'].isna().value_counts()

False    8172
True     3742
Name: Market Category, dtype: int64

In [117]:
df['Vehicle Size'].isna().value_counts()

False    11914
Name: Vehicle Size, dtype: int64

In [119]:
df['Vehicle Style'].isna().value_counts()

False    11914
Name: Vehicle Style, dtype: int64

In [120]:
df.columns

Index(['Make', 'Model', 'Year', 'Engine Fuel Type', 'Engine HP',
       'Engine Cylinders', 'Transmission Type', 'Driven_Wheels',
       'Number of Doors', 'Market Category', 'Vehicle Size', 'Vehicle Style',
       'highway MPG', 'city mpg', 'Popularity', 'MSRP'],
      dtype='object')

In [121]:
df['highway MPG'].isna().value_counts()

False    11914
Name: highway MPG, dtype: int64

In [122]:
df['city mpg'].isna().value_counts()

False    11914
Name: city mpg, dtype: int64

In [123]:
df['Popularity'].isna().value_counts()

False    11914
Name: Popularity, dtype: int64

In [124]:
df['MSRP'].isna().value_counts()

False    11914
Name: MSRP, dtype: int64

In [125]:
df['Engine Fuel Type'].isna().value_counts()

False    11911
True         3
Name: Engine Fuel Type, dtype: int64

### Question 6

In [127]:
df['Engine Cylinders'].describe()

count    11884.000000
mean         5.628829
std          1.780559
min          0.000000
25%          4.000000
50%          6.000000
75%          6.000000
max         16.000000
Name: Engine Cylinders, dtype: float64

In [128]:
df['Engine Cylinders'].mode()

0    4.0
Name: Engine Cylinders, dtype: float64

In [129]:
df['Engine Cylinders'].isna().value_counts()

False    11884
True        30
Name: Engine Cylinders, dtype: int64

In [132]:
df['Engine Cylinders'].fillna(4,inplace = True)

In [133]:
df['Engine Cylinders'].isna().value_counts()

False    11914
Name: Engine Cylinders, dtype: int64

In [135]:
df['Engine Cylinders'].median()

6.0

### Question 7

In [164]:
lotus = df[(df['Make']=="Lotus")]
lotus = lotus[['Engine HP', 'Engine Cylinders']]
array=lotus.drop_duplicates()

In [165]:
array


Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [166]:
x=array.to_numpy()

In [167]:
x

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [168]:
xt = x.transpose()

In [169]:
xt

array([[189., 218., 217., 350., 400., 276., 345., 257., 240.],
       [  4.,   4.,   4.,   8.,   6.,   6.,   6.,   4.,   4.]])

In [170]:
xtx = np.matmul(xt,x)
xtx

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [172]:
xtx_=inv(xtx)
xtx_

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [174]:
y= np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])
y

array([1100,  800,  750,  850, 1300, 1000, 1000, 1300,  800])

In [175]:
xxtx_ = np.matmul(xtx_,xt)
xxtx_

array([[-1.31950096e-03,  2.84443321e-04,  2.29134897e-04,
        -4.18763778e-03,  4.46417989e-03, -2.39406462e-03,
         1.42221660e-03,  2.44147184e-03,  1.50122864e-03],
       [ 8.60893170e-02,  7.36567735e-04,  3.67976598e-03,
         2.54588185e-01, -2.13748621e-01,  1.51207962e-01,
        -5.18727169e-02, -1.14048164e-01, -6.40137937e-02]])

In [176]:
w = np.matmul(xxtx_,y)

In [177]:
w

array([  4.59494481, -63.56432501])